source("functions2.R")
data <- readRDS('../data/usrds2')
alltype <- c('ip', 'op', 'sn', 'hh', 'hs', 'all')
h2 <- c(6.4, 68.5, 50.2, 45.6, 13.7, 9.1)
# load('../../cohort3_10p.RData')
# data <- data %>% transmute(pseudo_id = USRDS_ID, race = ifelse(RACE > 2, 3, RACE), sex = SEX, age = INC_AGE, hypertension, other_comorbid, bmi, log_sn = log(sn / 100 + 1), time1 = time - as.numeric(FIRST_SE), time2 = as.numeric(DIED) - time, time3 = time - as.numeric(TX1DATE))
group3 <- with(data, !is.na(time3) & time3 >= 0)
args <- commandArgs(trailingOnly = TRUE)
type <- as.numeric(args[1])
pres <- c()
for (i in 1:10) {
    temp <- readRDS(paste0('real_mixed_fit12_', alltype[type], '_part=', i))
    pres <- c(pres, temp)
}
res <- with(data[group3,], kres.p(matrix(1, sum(group3)), as.matrix(pres), time3, time2, 1:sum(group3), h2[type], 19))
teval <- c(seq(0, 800, 8), seq(0, 1600, 16), seq(0, 2200, 22))
seval <- c(seq(800, 0, -8), seq(1600, 0, -16), seq(2200, 0, -22))
coef <- with(data[group3,], kfit(matrix(1, sum(group3)), pres, time3, time2, teval, seval, h2[type]))
var <- with(data[group3,], sandwich(matrix(1, sum(group3)), res, pseudo_id, time3, time2, teval, seval, h2[type]))
list(coef = coef, var = var) %>% saveRDS(paste0('real_mixed_fit2_', alltype[type]))
