# setwd('..')
source("functions2.R")
# cl <- makeCluster(20)
# RACE == 2, RACE > 2, SEX == 2, INC_AGE, hypertension, other_comorbid, bmi >= 25, bmi >= 30, log(claim / 100 + 1), time - as.numeric(FIRST_SE), as.numeric(DIED) - time, time - as.numeric(TX1DATE), USRDS_ID
# load("cohort23_10p.RData")
# d <- attach.big.matrix("cohort23_10p.desc")
# group2 <- is.na(d[,12])
# uniq_id <- unique(d[group2,13])
load('../data/usrds2.RData')
# data2 <- data
# load('cohort3_10p.RData')
# data <- data2 %>% bind_rows(data)
uniq_id <- unique(data$USRDS_ID)
set.seed(123)
id_by_folds <- split(sample(uniq_id), rep(1:5, length.out = length(uniq_id)))
args <- commandArgs(trailingOnly = TRUE)
h <- as.numeric(args[1])
fold <- as.numeric(args[2])
# train <- d[,13] %in% unlist(id_by_folds[-fold])
train <- data$USRDS_ID %in% unlist(id_by_folds[-fold])
# test <- d[,13] %in% id_by_folds[[fold]]
test <- data$USRDS_ID %in% id_by_folds[[fold]]
# cl <- makeCluster(19)
# fit <- kfitp(cbind(1, d[train, 1:8]), d[train, 9], d[train, 10], d[train, 11], d[test, 10], d[test, 11], h, 19)
fit <- with(data, kfit.p(cbind(1, RACE == 2, RACE > 2, SEX == 2, INC_AGE, hypertension, other_comorbid, bmi >= 25, bmi >= 30)[train,], log(ip+op+sn+hh+hs/100+1)[train], time[train] - as.numeric(FIRST_SE[train]), as.numeric(DIED[train]) - time[train], time[test] - as.numeric(FIRST_SE[test]), as.numeric(DIED[test]) - time[test], h, 19))
# stopCluster(cl)
# save(fit, file = paste0('real_mixed_cv1_h=', args[1], '_fold=', args[2], '.RData'))
# res <- d[test, 9] - rowSums(cbind(1, d[test, 1:8]) * fit)
res <- with(data[test, ], log(ip+op+sn+hh+hs/100+1) - rowSums(cbind(1, RACE == 2, RACE > 2, SEX == 2, INC_AGE, hypertension, other_comorbid, bmi >= 25, bmi >= 30) * fit))
data.frame(h = h, fold = fold, sse = sum(res^2, na.rm = T), nobs = sum(!is.na(res))) %>% saveRDS(paste0('real_mixed_cv1/all_h=', args[1], '_fold=', args[2]))
